spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: sprincloud-config-kang-dev
---
spring:
  profiles: test #测试环境
  application:
    name: springcloud-zuul
#请保存UTF-8格式