server:
  port: 9527
spring:
  application:
    name: springcloud-zuul-gateway
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true
    fetch-registry: true #是否从EurekaServer抓取已有得注册信息，默认为true,集群时必须设置true才能配合Ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/
zuul:
  prefix: /kang  #增加统一的访问前缀
  routes:
    mydept.serviceId: cloud-payment-service #访问得客户端在eureka中得名字
    mydept.path: /payment/get/**  #访问得地址
  ignored-services: cloud-payment-service #忽略通过服务名可以访问微服务(添加完成之后不能通过服务名访问微服务)
  servlet-path: /
ip:
  addr:   ["eureka7001.com"]